//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PinMAME32.rc
//
#define IDPAUSE                         3
#define IDAPPLY                         4
#define IDS_UI_FILE                     71
#define IDS_UI_VIEW                     72
#define IDS_UI_OPTIONS                  73
#define IDS_UI_HELP                     74
#define IDS_UI_TOOLBAR                  81
#define IDS_UI_STATUSBAR                82
#define IDS_UI_FOLDERLIST               83
#define IDS_UI_SCREENSHOT               84
#define IDS_UI_SPACER1                  85
#define IDS_UI_LARGEICONS               86
#define IDS_UI_SMALLICONS               87
#define IDS_UI_LIST                     88
#define IDS_UI_DETAILS                  89
#define IDS_UI_SPACER2                  90
#define IDS_UI_ARRANGE                  91
#define IDS_UI_LINEUPICONS              92
#define IDS_UI_REFRESH                  93
#define IDS_UI_CUSTOMIZE                94
#define IDD_MAIN                        101
#define IDA_TAB_KEYS                    106
#define IDI_MAME32_ICON                 107
#define IDD_ABOUT                       108
#define IDR_MAIN_MENU                   109
#define IDR_UI_MENU                     110
#define IDW_STATUS                      112
#define IDB_ABOUT                       113
#define IDD_DIRECTX                     114
#define IDD_AUDIT                       115
#define IDD_DIRECTORIES                 116
#define IDD_CUSTOM_FILE                 117
#define IDR_CONTEXT_MENU                118
#define IDI_WIN_NOROMS                  119
#define IDI_WIN_ROMS                    120
#define IDI_WIN_UNKNOWN                 121
#define IDI_WIN_CLONE                   122
#define IDI_WIN_REDX                    123
#define IDI_FOLDER_OPEN                 124
#define IDI_FOLDER                      125
#define IDI_FOLDER_AVAILABLE            126
#define IDI_FOLDER_MANUFACTURER         127
#define IDI_FOLDER_UNAVAILABLE          128
#define IDI_FOLDER_YEAR                 129
#define IDI_FOLDER_SOURCE               130
#define IDI_MANUFACTURER                131
#define IDI_WORKING                     132
#define IDI_NONWORKING                  133
#define IDI_YEAR                        134
#define IDI_SOUND                       135
#define IDI_CPU                         136
#define IDI_HARDDISK                    137
#define IDI_SOURCE                      138
#define IDR_CONTEXT_HEADER              151
#define IDD_PROP_GAME                   152
#define IDD_PROP_AUDIT                  153
#define IDD_PROP_DISPLAY                154
#define IDD_PROP_SOUND                  155
#define IDD_PROP_ADVANCED               156
#define IDD_PROP_INPUT                  157
#define IDD_PROP_MISC                   158
#define IDD_PROP_VECTOR                 159
#define IDD_COLUMNS                     160
#define IDI_KEYBOARD                    161
#define IDI_JOYSTICK                    162
#define IDI_DISPLAY                     163
#define IDI_CHECKMARK                   164
#define IDC_CURSOR_HSPLIT               165
#define IDB_TOOLBAR                     166
#define IDB_PROP_DISPLAY                167
#define IDR_CONTEXT_TREE                168
#define IDD_FILTERS                     169
#define IDD_RESET                       170
#define IDD_LOAD_PROGRESS               171
#define IDD_INTERFACE_OPTIONS           173
#define IDD_PROP_HISTORY                176
#define IDD_ROM_ERROR                   177
#define IDD_LANGUAGE                    178
#define IDD_ERROR                       179
#define IDR_CONTEXT_SCREENSHOT          181
#define IDI_HEADER_UP                   182
#define IDI_HEADER_DOWN                 183
#define IDD_PROP_DIRECT3D               184
#define IDD_PROP_PINMAME                185
#define IDC_LIST                        1000
#define IDC_PLAY                        1001
#define IDC_DISPLAYS                    1002
#define IDC_JOYSTICK                    1003
#define IDC_VECTORTEXT                  1004
#define IDC_SIZES                       1005
#define IDC_USE_TRAK                    1006
#define IDC_DISPLAYTYPE                 1007
#define IDC_TRAK_SENSITIVITY            1008
#define IDC_FRAMESKIP                   1009
#define IDC_ROTATE                      1010
#define IDC_HELP_TEXT                   1011
#define IDC_TAB                         1012
#define IDC_SCANLINES                   1013
#define IDC_CHEAT                       1014
#define IDC_LOG                         1015
#define IDC_SLEEP                       1016
#define IDC_BACKDROPS                   1017
#define IDC_ARTWORK_CROP                1018
#define IDC_OVERLAYS                    1019
#define IDC_LEDS                        1020
#define IDC_BEZELS                      1021
#define IDC_DDRAW                       1022
#define IDC_GAMMA                       1023
#define IDC_BRIGHTCORRECT               1024
#define IDC_USE_DEFAULT                 1025
#define IDC_VSCANLINES                  1026
#define IDC_SAMPLERATE                  1027
#define IDC_DEPTH                       1028
#define IDC_ANTIALIAS                   1029
#define IDC_BEAM                        1030
#define IDC_FLICKER                     1031
#define IDC_FLIPX                       1032
#define IDC_FLIPY                       1033
#define IDC_INTENSITY                   1034
#define IDC_DIRECTX_HELP                1035
#define IDB_WEB_PAGE                    1036
#define IDC_ROMS_PROGRESS               1037
#define IDC_ROMS_CORRECT                1038
#define IDC_ROMS_INCORRECT              1039
#define IDC_ROMS_TOTAL                  1040
#define IDC_SAMPLES_PROGRESS            1041
#define IDC_SAMPLES_CORRECT             1042
#define IDC_SAMPLES_INCORRECT           1043
#define IDC_SAMPLES_TOTAL               1044
#define IDC_AUDIT_DETAILS               1045
#define IDC_USE_FM_YM3812               1046
#define IDC_DIR_COMBO                   1047
#define IDC_DIR_LIST                    1048
#define IDC_DIR_BROWSE                  1049
#define IDC_DIR_INSERT                  1050
#define IDC_DIR_DELETE                  1051
#define IDC_FLICKERTEXT                 1052
#define IDC_INTENSITYTEXT               1053
#define IDC_SSFRAME                     1054
#define IDC_SSNONE                      1056
#define IDC_SSPICTURE                   1057
#define IDC_BEAMTEXT                    1058
#define IDC_COLORSTEXT                  1059
#define IDC_SIZETEXT                    1060
#define IDC_TRACKSPINTEXT               1061
#define IDC_INPUTDEVTEXT                1062
#define IDC_RATETEXT                    1063
#define IDC_LISTAVAILABLECOLUMNS        1064
#define IDC_LISTSHOWCOLUMNS             1065
#define IDC_BUTTONADD                   1066
#define IDC_BUTTONREMOVE                1067
#define IDC_BUTTONMOVEDOWN              1068
#define IDC_BUTTONMOVEUP                1069
#define IDC_PROP_SOUND                  1070
#define IDC_PROP_CPU                    1071
#define IDC_PROP_TITLE                  1072
#define IDC_PROP_MANUFACTURED           1073
#define IDC_PROP_STATUS                 1074
#define IDC_PROP_SCREEN                 1075
#define IDC_PROP_COLORS                 1076
#define IDC_PROP_ROMS                   1077
#define IDC_PROP_SAMPLES                1078
#define IDC_PROP_CLONEOF_TEXT           1079
#define IDC_PROP_CLONEOF                1080
#define IDC_TRANSLUCENCY                1081
#define IDC_VERSION                     1082
#define IDC_ARTWORK                     1083
#define IDC_BRIGHTNESS                  1084
#define IDC_GAMMADISP                   1085
#define IDC_BRIGHTNESSDISP              1086
#define IDC_BRIGHTCORRECTDISP           1087
#define IDC_FLICKERDISP                 1088
#define IDC_INTENSITYDISP               1089
#define IDC_BEAMDISP                    1090
#define IDC_AUTOFRAMESKIP               1091
#define IDC_TREE                        1092
#define IDC_WINDOWED                    1093
#define IDC_STEREO                      1094
#define IDC_PROP_RESET                  1095
#define IDC_SPLITTER                    1096
#define IDC_SPLITTER2                   1097
#define IDC_DIVIDER                     1098
#define IDC_FILTER_VECTOR               1099
#define IDC_FILTER_RASTER               1100
#define IDC_FILTER_UNAVAILABLE          1101
#define IDC_FILTER_NONWORKING           1102
#define IDC_FILTER_CLONES               1103
#define IDC_RESET_GAMES                 1105
#define IDC_RESET_UI                    1106
#define IDC_RESET_FILTERS               1107
#define IDC_LOAD_PROGRESS               1108
#define IDC_RESET_DEFAULT               1109
#define IDC_FILTER_ORIGINALS            1110
#define IDC_FILTER_WORKING              1111
#define IDC_FILTER_AVAILABLE            1112
#define IDC_CONFIGURETEXT               1113
#define IDC_JOYMAPTEXT                  1114
#define IDC_START_GAME_CHECK            1115
#define IDC_VOLUME                      1117
#define IDC_VOLUMEDISP                  1118
#define IDC_PROP_HISTORY                1119
#define IDC_HISTORY                     1120
#define IDC_SAMPLES                     1121
#define IDC_ERROR_DETAILS               1122
#define IDC_TRIPLE_BUFFER               1123
#define IDC_LOAD_ROMNAME                1124
#define IDC_DEFAULT_INPUT               1125
#define IDC_LANGUAGECHECK               1126
#define IDC_LANGUAGEBROWSE              1127
#define IDC_LANGUAGEEDIT                1128
#define IDC_FILTER_EDIT                 1129
#define IDC_ABOUT                       1130
#define IDC_PROP_DISPLAY                1131
#define IDC_USE_FILTER                  1132
#define IDC_USE_SOUND                   1133
#define IDC_WAITVSYNC                   1134
#define IDC_HWSTRETCH                   1135
#define IDC_SWITCHRES                   1136
#define IDC_SWITCHBPP                   1137
#define IDC_MAXIMIZE                    1138
#define IDC_KEEPASPECT                  1139
#define IDC_MATCHREFRESH                1140
#define IDC_SYNCREFRESH                 1141
#define IDC_USE_MOUSE                   1143
#define IDC_THROTTLE                    1144
#define IDC_RESDEPTH                    1145
#define IDC_VOLUMETEXT                  1146
#define IDC_RESDEPTHTEXT                1147
#define IDC_REFRESH                     1148
#define IDC_REFRESHTEXT                 1149
#define IDC_EFFECT                      1150
#define IDC_BRIGHTNESSTEXT              1151
#define IDC_STEADYKEY                   1152
#define IDC_ASPECTRATIO                 1153
#define IDC_ASPECTRATION                1154
#define IDC_ASPECTRATIOD                1155
#define IDC_ASPECTRATIOTEXT             1156
#define IDC_JOY_GUI                     1157
#define IDC_BROADCAST                   1158
#define IDC_ARTRES                      1159
#define IDC_A2D                         1160
#define IDC_A2DDISP                     1161
#define IDC_A2DTEXT                     1162
#define IDC_ARTRESTEXT                  1163
#define IDC_PLAY_GAME                   1164
#define IDC_LIGHTGUN                    1165
#define IDC_SSTAB                       1167
#define IDC_GAME_ICON                   1168
#define IDC_RANDOM_BG                   1169
#define IDC_CUSTOM_TREE                 1170
#define IDC_CUSTOMFILEBROWSE            1171
#define IDC_CUSTOMFILE_GAME             1172
#define IDC_LOAD_STATUS                 1173
#define IDC_ERROR_TEXT                  1174
#define IDC_ARTMISCTEXT                 1175
#define IDC_SKIP_DISCLAIMER             1176
#define IDC_SKIP_GAME_INFO              1177
#define IDC_PROP_SOURCE                 1177
#define IDC_OLD_TIMING                  1178
#define IDC_PAUSEBRIGHT                 1180
#define IDC_PAUSEBRIGHTDISP             1181
#define IDC_HIGH_PRIORITY               1182
#define IDC_D3D                         1183
#define IDC_D3D_FILTER                  1184
#define IDC_D3D_TEXTURE_MANAGEMENT      1185
#define IDC_AUDIO_LATENCY               1186
#define IDC_D3D_EFFECT                  1187
#define IDC_D3D_PRESCALE                1189
#define IDC_D3D_ROTATE_EFFECTS          1190
#define IDC_CLEAN_STRETCH               1191
#define IDC_AUDIO_LATENCY_DISP          1192
#define IDC_D3D_SCANLINES               1193
#define IDC_D3D_SCANLINES_ENABLE        1194
#define IDC_D3D_SCANLINES_DISP          1195
#define IDC_D3D_FEEDBACK_ENABLE         1199
#define IDC_D3D_FEEDBACK                1200
#define IDC_D3D_FEEDBACK_DISP           1201
#define IDC_ZOOM                        1202
#define IDC_ZOOMDIST                    1203
#define IDC_BIOS                        1204
#define IDC_HIDE_MOUSE                  1205
#define IDC_AUDIT_DETAILS_PROP          1206
#define IDC_CYCLE_SCREENSHOT            1209
#define IDC_CYCLETIME                   1210
#define IDC_CYCLETIMESEC                1211
#define IDC_AUDIO_LATENCY_TEXT          1212
#define IDC_STRETCH_SCREENSHOT_LARGER   1213
#define ID_CONTEXT_SHOW_FOLDER_START    39000
#define ID_CONTEXT_SHOW_FOLDER_END      39200
#define IDC_DMD_ONLY                    1230
#define IDC_DMD_COMPACT                 1231
#define IDC_DMD_ANTIALIAS_TEXT          1232
#define IDC_DMD_ANTIALIAS               1233
#define IDC_DMD_ANTIALIAS_DISP          1234
#define IDC_DMD_PERC0_TEXT              1235
#define IDC_DMD_PERC0                   1236
#define IDC_DMD_PERC0_DISP              1237
#define IDC_DMD_PERC33_TEXT             1238
#define IDC_DMD_PERC33                  1239
#define IDC_DMD_PERC33_DISP             1240
#define IDC_DMD_PERC66_TEXT             1241
#define IDC_DMD_PERC66                  1242
#define IDC_DMD_PERC66_DISP             1243
#define IDC_DMD_RED_TEXT                1244
#define IDC_DMD_RED                     1245
#define IDC_DMD_RED_DISP                1246
#define IDC_DMD_GREEN_TEXT              1247
#define IDC_DMD_BLUE_TEXT               1248
#define IDC_DMD_GREEN                   1249
#define IDC_DMD_BLUE                    1250
#define IDC_DMD_GREEN_DISP              1251
#define IDC_DMD_BLUE_DISP               1252
#define ID_FILE_EXIT                    40001
#define ID_ABOUT                        40003
#define ID_FILE_PLAY                    40004
#define ID_HELP_ABOUT                   40006
#define ID_VIEW_LARGE_ICON              40007
#define ID_VIEW_SMALL_ICON              40008
#define ID_VIEW_LIST_MENU               40009
#define ID_VIEW_DETAIL                  40010
#define ID_VIEW_GROUPED                 40011
#define ID_OPTIONS_FONT                 40012
#define ID_OPTIONS_CLONE_COLOR          40013
#define ID_OPTIONS_DIR                  40014
#define ID_OPTIONS_DEFAULTS             40015
#define ID_OPTIONS_RESET_DEFAULTS       40016
#define ID_OPTIONS_INTERFACE            40017
#define ID_FILE_AUDIT                   40018
#define ID_FILE_PLAY_RECORD             40019
#define ID_FILE_PLAY_BACK               40020
#define ID_VIEW_PICTURE_AREA            40023
#define ID_HELP_CONTENTS                40025
#define ID_HELP_WHATS_NEW32             40026
#define ID_HELP_TROUBLE                 40027
#define ID_HELP_RELEASE                 40028
#define ID_HELP_WHATS_NEW               40029
#define ID_HELP_CHEATS                  40030
#define ID_VIEW_BYGAME                  40034
#define ID_VIEW_BYDIRECTORY             40035
#define ID_VIEW_BYMANUFACTURER          40036
#define ID_VIEW_BYYEAR                  40037
#define ID_VIEW_BYTYPE                  40038
#define ID_VIEW_BYTIMESPLAYED           40039
#define ID_VIEW_LINEUPICONS             40040
#define ID_UPDATE_GAMELIST              40042
#define ID_SORT_ASCENDING               40045
#define ID_SORT_DESCENDING              40046
#define ID_CUSTOMIZE_FIELDS             40048
#define ID_GAME_PROPERTIES              40049
#define ID_VIEW_PAGETAB                 40050
#define ID_VIEW_FOLDERS                 40051
#define ID_VIEW_TOOLBARS                40052
#define ID_VIEW_STATUS                  40053
#define ID_CONTEXT_FILTERS              40054
#define ID_CONTEXT_RENAME_CUSTOM        40055
#define ID_CONTEXT_ADD_CUSTOM           40057
#define ID_CONTEXT_REMOVE_CUSTOM        40058
#define ID_GAME_AUDIT                   40059
#define ID_CONTEXT_SELECT_RANDOM        40060
#define ID_OPTIONS_LANGUAGE             40061
#define ID_VIEW_TAB_SCREENSHOT          40062
#define ID_VIEW_TAB_FLYER               40063
#define ID_VIEW_TAB_CABINET             40064
#define ID_VIEW_TAB_MARQUEE             40065
#define ID_VIEW_TAB_TITLE               40066
#define ID_VIEW_TAB_CONTROL_PANEL       40067
#define ID_VIEW_TAB_HISTORY             40068
#define ID_OPTIONS_BG                   40070
#define ID_TOGGLE_TAB_SCREENSHOT        40071
#define ID_TOGGLE_TAB_FLYER             40072
#define ID_TOGGLE_TAB_CABINET           40073
#define ID_TOGGLE_TAB_MARQUEE           40074
#define ID_TOGGLE_TAB_TITLE             40075
#define ID_TOGGLE_TAB_CONTROL_PANEL     40076
#define ID_TOGGLE_TAB_HISTORY           40077
#define ID_VIEW_FULLSCREEN              40079
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         40080
#define _APS_NEXT_CONTROL_VALUE         1253
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
