//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mame32.rc
//
#define IDPAUSE                         3
#define IDAPPLY                         4
#define IDS_UI_FILE                     71
#define IDS_UI_VIEW                     72
#define IDS_UI_OPTIONS                  73
#define IDS_UI_HELP                     74
#define IDS_UI_TOOLBAR                  81
#define IDS_UI_STATUSBAR                82
#define IDS_UI_FOLDERLIST               83
#define IDS_UI_SCREENSHOT               84
#define IDS_UI_SPACER1                  85
#define IDS_UI_LARGEICONS               86
#define IDS_UI_SMALLICONS               87
#define IDS_UI_LIST                     88
#define IDS_UI_DETAILS                  89
#define IDS_UI_SPACER2                  90
#define IDS_UI_ARRANGE                  91
#define IDS_UI_LINEUPICONS              92
#define IDS_UI_REFRESH                  93
#define IDS_UI_CUSTOMIZE                94
#define IDD_MAIN                        101
#define IDD_HELP                        104
#define IDA_TAB_KEYS                    106
#define IDI_MAME32_ICON                 107
#define IDD_ABOUT                       108
#define IDR_MAIN_MENU                   109
#define IDR_UI_MENU                     110
#define IDW_STATUS                      112
#define IDB_ABOUT                       113
#define IDD_DIRECTX                     114
#define IDD_AUDIT                       115
#define IDD_DIRECTORIES                 116
#define IDR_CONTEXT_MENU                123
#define IDI_WIN_NOROMS                  124
#define IDI_WIN_ROMS                    125
#define IDI_WIN_UNKNOWN                 126
#define IDI_WIN_REDX                    127
#define IDI_FOLDER_OPEN                 128
#define IDI_FOLDER                      129
#define IDI_FOLDER_AVAILABLE            130
#define IDI_FOLDER_FAVORITES            131
#define IDI_FOLDER_MANUFACTURER         132
#define IDI_FOLDER_UNAVAILABLE          133
#define IDI_FOLDER_YEAR                 134
#define IDI_MANUFACTURER                135
#define IDI_WORKING                     136
#define IDI_NONWORKING                  137
#define IDI_YEAR                        138
#define IDI_SOUND                       139
#define IDI_NEOGEO                      140
#define IDR_CONTEXT_HEADER              151
#define IDD_PROP_GAME                   152
#define IDD_PROP_AUDIT                  153
#define IDD_PROP_DISPLAY                154
#define IDD_PROP_SOUND                  155
#define IDD_PROP_ADVANCED               156
#define IDD_PROP_INPUT                  157
#define IDD_PROP_MISC                   158
#define IDD_PROP_VECTOR                 159
#define IDD_COLUMNS                     160
#define IDI_KEYBOARD                    161
#define IDI_JOYSTICK                    162
#define IDI_DISPLAY                     163
#define IDI_CHECKMARK                   164
#define IDC_CURSOR_HSPLIT               165
#define IDB_TOOLBAR                     166
#define IDB_PROP_DISPLAY                167
#define IDR_CONTEXT_TREE                168
#define IDD_FILTERS                     169
#define IDD_RESET                       170
#define IDD_LOAD_PROGRESS               171
#define IDD_START_OPTIONS               173
#define IDD_PROP_HISTORY                176
#define IDD_ROM_ERROR                   177
#define IDD_LANGUAGE                    178
#define IDD_ERROR                       179
#define IDD_PROP_PINMAME                180
#define IDC_LIST                        1000
#define IDC_PLAY                        1001
#define IDC_DISPLAYS                    1004
#define IDC_JOYSTICK                    1005
#define IDC_VECTORTEXT                  1006
#define IDC_SIZES                       1007
#define IDC_USE_TRAK                    1008
#define IDC_DISPLAYTYPE                 1010
#define IDC_TRAK_SENSITIVITY            1011
#define IDC_FRAMESKIP                   1012
#define IDC_ROTATE                      1014
#define IDC_HELP_TEXT                   1019
#define IDC_TAB                         1020
#define IDC_SCANLINES                   1026
#define IDC_CHEAT                       1033
#define IDC_LOG                         1034
#define IDC_DDRAW                       1041
#define IDC_GAMMA                       1044
#define IDC_USE_DEFAULT                 1051
#define IDC_VSCANLINES                  1052
#define IDC_DIRTY                       1053
#define IDC_SAMPLERATE                  1054
#define IDC_DEPTH                       1060
#define IDC_ANTIALIAS                   1061
#define IDC_BEAM                        1062
#define IDC_FLICKER                     1063
#define IDC_FLIPX                       1064
#define IDC_FLIPY                       1065
#define IDC_DIRECTX_HELP                1067
#define IDB_WEB_PAGE                    1068
#define IDC_ROMS_PROGRESS               1069
#define IDC_ROMS_CORRECT                1070
#define IDC_ROMS_INCORRECT              1071
#define IDC_ROMS_TOTAL                  1072
#define IDC_SAMPLES_PROGRESS            1073
#define IDC_SAMPLES_CORRECT             1074
#define IDC_SAMPLES_INCORRECT           1075
#define IDC_SAMPLES_TOTAL               1076
#define IDC_AUDIT_DETAILS               1078
#define IDC_USE_FM_YM3812               1079
#define IDC_DIR_COMBO                   1085
#define IDC_DIR_LIST                    1086
#define IDC_DIR_BROWSE                  1087
#define IDC_DIR_INSERT                  1088
#define IDC_DIR_DELETE                  1089
#define IDC_FLICKERTEXT                 1096
#define IDC_SSFRAME                     1103
#define IDC_SSDEFPIC                    1110
#define IDC_SSNONE                      1111
#define IDC_SSPICTURE                   1112
#define IDC_BEAMTEXT                    1113
#define IDC_COLORSTEXT                  1114
#define IDC_SIZETEXT                    1117
#define IDC_TRACKSPINTEXT               1118
#define IDC_INPUTDEVTEXT                1119
#define IDC_RATETEXT                    1121
#define IDC_LISTAVAILABLECOLUMNS        1123
#define IDC_LISTSHOWCOLUMNS             1124
#define IDC_BUTTONADD                   1125
#define IDC_BUTTONREMOVE                1126
#define IDC_BUTTONMOVEDOWN              1127
#define IDC_BUTTONMOVEUP                1128
#define IDC_PROP_SOUND                  1129
#define IDC_PROP_CPU                    1130
#define IDC_PROP_TITLE                  1131
#define IDC_PROP_MANUFACTURED           1132
#define IDC_PROP_STATUS                 1133
#define IDC_PROP_SCREEN                 1134
#define IDC_PROP_COLORS                 1135
#define IDC_PROP_ROMS                   1136
#define IDC_PROP_SAMPLES                1137
#define IDC_PROP_CLONEOF_TEXT           1140
#define IDC_PROP_CLONEOF                1141
#define IDC_TRANSLUCENCY                1142
#define IDC_VERSION                     1143
#define IDC_ARTWORK                     1145
#define IDC_BRIGHTNESS                  1146
#define IDC_GAMMADISP                   1147
#define IDC_BRIGHTNESSDISP              1148
#define IDC_FLICKERDISP                 1149
#define IDC_BEAMDISP                    1151
#define IDC_AUTOFRAMESKIP               1152
#define IDC_TREE                        1153
#define IDC_WINDOWED                    1156
#define IDC_STEREO                      1157
#define IDC_PROP_RESET                  1158
#define IDC_SPLITTER                    1169
#define IDC_SPLITTER2                   1170
#define IDC_DIVIDER                     1172
#define IDC_FILTER_VECTOR               1173
#define IDC_FILTER_RASTER               1174
#define IDC_FILTER_UNAVAILABLE          1176
#define IDC_FILTER_NONWORKING           1177
#define IDC_FILTER_CLONES               1178
#define IDC_FILTER_NEOGEO               1179
#define IDC_RESET_GAMES                 1181
#define IDC_RESET_UI                    1182
#define IDC_RESET_FILTERS               1183
#define IDC_LOAD_PROGRESS               1185
#define IDC_RESET_DEFAULT               1186
#define IDC_FILTER_ORIGINALS            1187
#define IDC_FILTER_WORKING              1188
#define IDC_FILTER_AVAILABLE            1190
#define IDC_CONFIGURETEXT               1199
#define IDC_JOYMAPTEXT                  1207
#define IDC_START_GAME_CHECK            1209
#define IDC_START_VERSION_WARN          1210
#define IDC_VOLUME                      1225
#define IDC_VOLUMEDISP                  1226
#define IDC_PROP_HISTORY                1227
#define IDC_HISTORY                     1227
#define IDC_SAMPLES                     1228
#define IDC_ERROR_DETAILS               1229
#define IDC_TRIPLE_BUFFER               1230
#define IDC_LOAD_ROMNAME                1231
#define IDC_DEFAULT_INPUT               1232
#define IDC_LANGUAGECHECK               1233
#define IDC_LANGUAGEBROWSE              1234
#define IDC_LANGUAGEEDIT                1236
#define IDC_FILTER_EDIT                 1237
#define IDC_ABOUT                       1238
#define IDC_PROP_DISPLAY                1239
#define IDC_USE_FILTER                  1240
#define IDC_USE_SOUND                   1241
#define IDC_WAITVSYNC                   1242
#define IDC_HWSTRETCH                   1244
#define IDC_SWITCHRES                   1245
#define IDC_SWITCHBPP                   1246
#define IDC_MAXIMIZE                    1247
#define IDC_KEEPASPECT                  1248
#define IDC_MATCHREFRESH                1249
#define IDC_SYNCREFRESH                 1250
#define IDC_NOROTATE                    1251
#define IDC_USE_MOUSE                   1252
#define IDC_THROTTLE                    1253
#define IDC_RESDEPTH                    1256
#define IDC_VOLUMETEXT                  1257
#define IDC_RESDEPTHTEXT                1259
#define IDC_REFRESH                     1260
#define IDC_REFRESHTEXT                 1261
#define IDC_EFFECT                      1262
#define IDC_BRIGHTNESSTEXT              1265
#define IDC_STEADYKEY                   1267
#define IDC_ASPECTRATIO                 1268
#define IDC_ASPECTRATION                1268
#define IDC_ASPECTRATIOD                1269
#define IDC_ASPECTRATIOTEXT             1270
#define IDC_JOY_GUI                     1271
#define IDC_BROADCAST                   1272
#define IDC_DMD_ONLY                    1275
#define IDC_DMD_COMPACT                 1276
#define IDC_DMD_ANTIALIAS_TEXT          1277
#define IDC_DMD_ANTIALIAS               1278
#define IDC_DMD_ANTIALIAS_DISP          1279
#define IDC_DMD_PERC0_TEXT              1280
#define IDC_DMD_PERC0                   1281
#define IDC_DMD_PERC0_DISP              1282
#define IDC_DMD_PERC33_TEXT             1283
#define IDC_DMD_PERC33                  1284
#define IDC_DMD_PERC33_DISP             1285
#define IDC_DMD_PERC66_TEXT             1286
#define IDC_DMD_PERC66                  1287
#define IDC_DMD_PERC66_DISP             1288
#define IDC_DMD_RED_TEXT                1289
#define IDC_DMD_RED                     1290
#define IDC_DMD_RED_DISP                1291
#define IDC_DMD_GREEN_TEXT              1292
#define IDC_DMD_BLUE_TEXT               1293
#define IDC_DMD_GREEN                   1294
#define IDC_DMD_BLUE                    1295
#define IDC_DMD_GREEN_DISP              1296
#define IDC_DMD_BLUE_DISP               1297
#define ID_FILE_EXIT                    40001
#define ID_ABOUT                        40003
#define ID_FILE_PLAY                    40004
#define ID_HELP_ABOUT                   40006
#define ID_VIEW_ICON                    40007
#define ID_VIEW_SMALL_ICON              40008
#define ID_VIEW_LIST_MENU               40009
#define ID_VIEW_DETAIL                  40010
#define ID_OPTIONS_DEFAULTS             40011
#define ID_OPTIONS_FONT                 40012
#define ID_OPTIONS_DIR                  40013
#define ID_OPTIONS_RESET_DEFAULTS       40014
#define ID_OPTIONS_STARTUP              40015
#define IDC_PLAY_GAME                   40016
#define ID_FILE_AUDIT                   40018
#define ID_FILE_PLAY_RECORD             40019
#define ID_FILE_PLAY_BACK               40020
#define ID_VIEW_SCREEN_SHOT             40023
#define ID_HELP_CONTENTS                40025
#define ID_HELP_WHATS_NEW32             40026
#define ID_HELP_SUPPORT                 40027
#define ID_HELP_RELEASE                 40028
#define ID_HELP_WHATS_NEW               40029
#define ID_HELP_CHEATS                  40030
#define ID_VIEW_BYGAME                  40034
#define ID_VIEW_BYDIRECTORY             40035
#define ID_VIEW_BYMANUFACTURER          40036
#define ID_VIEW_BYYEAR                  40037
#define ID_VIEW_BYTYPE                  40038
#define ID_VIEW_BYTIMESPLAYED           40039
#define ID_VIEW_LINEUPICONS             40040
#define ID_UPDATE_GAMELIST              40042
#define ID_SORT_ASCENDING               40045
#define ID_SORT_DESCENDING              40046
#define ID_CUSTOMIZE_FIELDS             40048
#define ID_GAME_PROPERTIES              40049
#define ID_VIEW_FOLDERS                 40051
#define ID_VIEW_TOOLBARS                40052
#define ID_VIEW_STATUS                  40053
#define ID_CONTEXT_FILTERS              40054
#define ID_CONTEXT_ADD_FAVORITE         40055
#define ID_CONTEXT_DEL_FAVORITE         40056
#define ID_GAME_AUDIT                   40059
#define ID_CONTEXT_SELECT_RANDOM        40060
#define ID_OPTIONS_LANGUAGE             40061
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         40062
#define _APS_NEXT_CONTROL_VALUE         1283
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
