/************************************************************************************************
  Midway Pinball 2000 (Revenge From Mars, Star Wars Episode I)

  Bring-up driver. The machine itself lives in src/p2k/ (see src/p2k/README.md): a MediaGX PC
  imported from MAME with its own bus and device tree. This file is only what PinMAME needs to
  instantiate that CPU - a machine driver and a game definition - so that PinMAME's own
  facilities, the remote debugger above all, can attach to it.

  It is deliberately not the finished driver: the P2K machine still assembles itself and loads
  its ROMs through p2k_state, and the pinball I/O is not mapped onto PinMAME's switch, lamp and
  solenoid model yet.
 ************************************************************************************************/
#include "driver.h"
#include "core.h"
#include "sndbrd.h"
#include "wmssnd.h"
#include "p2k_names.h"   /* generated by tools/extract_p2k_names.py */

static int p2k_bringupFrame;   /* SCAFFOLDING: shared clock, see the block below */
static int p2k_keyLaunch;      /* Launch Ball key, shared with the scaffolding - see there */

#if defined(PINMAME) && (HAS_MEDIAGX)

/* implemented in src/p2k/p2k_pinmame.cpp */
extern void p2k_pinmame_start(const char *game);
extern void p2k_pinmame_stop(void);
extern void p2k_pinmame_nvram_set(int which, const unsigned char *data, unsigned size);
extern unsigned p2k_pinmame_nvram_get(int which, unsigned char *data, unsigned size);
extern UINT32 p2k_pinmame_read(offs_t address, UINT32 mem_mask);
extern void p2k_pinmame_write(offs_t address, UINT32 data, UINT32 mem_mask);
extern unsigned p2k_pinmame_frame(UINT32 *dest, unsigned capacity, unsigned *width, unsigned *height);
extern void p2k_pinmame_push_switches(const unsigned char *matrix, unsigned count);
extern void p2k_pinmame_pull_outputs(unsigned char *lamps, unsigned lamp_columns, UINT32 *solenoids, UINT32 *solenoids2);

static READ32_HANDLER(p2k_r)  { return p2k_pinmame_read(offset * 4, ~mem_mask); }
static WRITE32_HANDLER(p2k_w) { p2k_pinmame_write(offset * 4, data, ~mem_mask); }

/* The subsystem decodes addresses itself, but PinMAME's memory system wants the regions spelled
   out - a single entry spanning the whole 32-bit space keeps the CPU from being set up at all.
   These are the same ranges p2k_state::mem_r handles. */
#define P2K_RANGES(handler) \
	{ 0x00000000, 0x000FFFFF, handler },   /* low memory: RAM, CGA, expansion ROM, BIOS RAM */ \
	{ 0x00100000, 0x0FFFFFFF, handler },   /* extended RAM                                  */ \
	{ 0x10000000, 0x1FFFFFFF, handler },   /* PLX EEPROM, NVRAM, update flash, DCS, prism    */ \
	{ 0x40000000, 0x40BFFFFF, handler },   /* MediaGX registers, SMM, frame buffer           */ \
	{ 0xC0000000, 0xC000FFFF, handler },   /* alias of the MediaGX control registers         */ \
	{ 0xF00C0000, 0xF00C7FFF, handler },   /* second window on the expansion ROM             */ \
	{ 0xFFFD0000, 0xFFFFFFFF, handler },   /* system BIOS, holds the reset vector            */

static MEMORY_READ32_START(p2k_readmem)
	P2K_RANGES(p2k_r)
MEMORY_END

static MEMORY_WRITE32_START(p2k_writemem)
	P2K_RANGES(p2k_w)
MEMORY_END

/* Pinball 2000 has no DMD: the picture is the MediaGX frame buffer, 640x240 in RGB555 as the
   display controller is programmed here. What sits in video memory is rotated by 180 degrees
   against what a player sees - the cabinet reflects the monitor into the playfield through a
   half-silvered mirror, which accounts for one axis, and the frame buffer's row order for the
   other - so it is turned back here. What is on this screen is what a player sees. */
#define P2K_MAX_PIXELS (1024*768)

/* The display controller hands out 240 lines and the monitor shows 480: the picture is
   line-doubled on the way to the CRT, which is why the machine's pixels are twice as tall as
   they are wide. MAME's driver does not model this - its screen is set_raw(..., 640, 0, 640,
   256, 0, 240) - so a MAME screenshot has the aspect ratio wrong and this one does not. The
   user's own QEMU implementation of this machine documents the same thing at the same place:
   "Source is 640x240 RGB555 ... Output is 640x480 ARGB8888, line-doubled and Y-flipped".
   Doubling here rather than in the subsystem keeps the machine's own frame_rgb() honest about
   what its framebuffer holds, and gives the doubled picture to everything downstream at once -
   the window, libpinmame, and any frontend behind it. */
#define P2K_LINE_DOUBLE 2

/* The DCS2 sound board, upstream's (src/wpc/wmssnd.c, docs/pin2k_sound.md). On real hardware it
   lives in the Prism card's BAR4 window at 0x13000000:

     byte offset 0, word access - command write / response read
     byte offset 0, byte access - echo, the host's liveness probe
     byte offset 2              - status flags

   The subsystem calls these two for anything in that window; they are weak there, so the
   standalone harness links without a sound board. Upstream's own note is that their board is
   complete below the protocol and silent because "the stream lives in the PC-side game code" -
   this is that game code, so P2K_DCSLOG=1 writes down every word it sends. */
UINT32 p2k_dcs_read(UINT32 offset, UINT32 mem_mask);
void p2k_dcs_write(UINT32 offset, UINT32 data, UINT32 mem_mask);

/* P2K_SOLWATCH=1: log every change of the pinball board's register 0x0c, the low byte of
   solenoids2 - drivers 33-40, where the flipper coils live. Sampled at two points, see the note
   at the second one. A change log rather than a periodic sample: a power stroke lasts about three
   frames and a sample walks straight past it. */
static int p2k_solwatch(void) {
  static int on = -1;
  if (on < 0) on = getenv("P2K_SOLWATCH") ? 1 : 0;
  return on;
}

static int p2k_dcs_log(void) {
  static int on = -1;
  if (on < 0) on = getenv("P2K_DCSLOG") ? 1 : 0;
  return on;
}

/* The subsystem hands out dword-aligned addresses with the byte lanes in the mask, so the byte
   offset and the access width both have to be recovered from it: the lane of the first active
   byte gives the offset, the number of active bytes gives the width. Reading `offset & 3`
   directly puts every status access - byte offset 2, mask 0xffff0000 - into the echo path. */
static void p2k_dcs_decode(UINT32 offset, UINT32 mem_mask, unsigned *byte_off, unsigned *width,
                           unsigned *shift) {
  unsigned lane = 0, n = 0, i;
  while (lane < 4 && !((mem_mask >> (lane * 8)) & 0xff)) lane++;
  for (i = 0; i < 4; i++) if ((mem_mask >> (i * 8)) & 0xff) n++;
  if (lane > 3) lane = 0;
  *byte_off = ((offset & ~3u) + lane) & 3u;
  *width = n;
  *shift = lane * 8;
}

UINT32 p2k_dcs_read(UINT32 offset, UINT32 mem_mask) {
  unsigned byte_off, width, shift;
  UINT32 value;
  const char *what;
  p2k_dcs_decode(offset, mem_mask, &byte_off, &width, &shift);
  if (byte_off == 2)      { value = dcs_p2k_status_r(); what = "status"; }
  else if (width >= 2)    { value = dcs_p2k_data_r();   what = "data"; }
  else                    { value = dcs_p2k_echo_r();   what = "echo"; }
  if (p2k_dcs_log())
    fprintf(stderr, "[p2k dcs] r %s -> %04x\n", what, value);
  return value << shift;
}

void p2k_dcs_write(UINT32 offset, UINT32 data, UINT32 mem_mask) {
  unsigned byte_off, width, shift;
  UINT32 value;
  const char *what;
  p2k_dcs_decode(offset, mem_mask, &byte_off, &width, &shift);
  value = (data >> shift) & (width >= 2 ? 0xffffu : 0xffu);
  what = (byte_off == 2) ? "status" : (width >= 2 ? "data" : "echo");
  if (p2k_dcs_log())
    fprintf(stderr, "[p2k dcs] w %s <- %04x\n", what, value);
  if (byte_off == 2)   dcs_p2k_status_w((UINT16)value);
  else if (width >= 2) dcs_p2k_data_w((UINT16)value);
  else                 dcs_p2k_echo_w((UINT8)value);
}

/* The pinball I/O meets PinMAME's core model here: the switch matrix goes down to the driver
   board, the lamp columns and coil bits come back. Once per frame is enough for lamps - the core
   integrates them anyway - and is the honest first step; if coils turn out to need finer timing,
   this is the place that moves.

   Which matrix position is which switch, and which bit is which coil, still needs Revenge From
   Mars' own tables. This is the path, not yet the map. */
static void p2k_sync_io(void) {
  UINT8 lamps[16];   /* eight driven columns, two row banks each */
  UINT32 solenoids = 0, solenoids2 = 0;
  int i;

  /* Let the core read the keyboard into its switch columns first - it is what calls our
     SWITCH_UPDATE handler. Nothing else in this driver drives it, so without this the cabinet
     and coin door keys never reach the machine. The flipper argument enables the core's
     end-of-stroke simulation, which this board does not report.

     Order matters here: core_updateSw() rewrites bits 0x02 and 0x08 of the flipper column from
     the flipper keys, and on this board those are the coin door switch and an unused position.
     It calls our handler afterwards, so our values win - but only in that order. */
  core_updateSw(FALSE);

  p2k_pinmame_push_switches((const unsigned char *)coreGlobals.swMatrix, CORE_MAXSWCOL);
  p2k_pinmame_pull_outputs(lamps, sizeof(lamps), &solenoids, &solenoids2);

  for (i = 0; i < (int)sizeof(lamps); i++)
    coreGlobals.lampMatrix[i] = lamps[i];
  coreGlobals.solenoids = solenoids;
  coreGlobals.solenoids2 = solenoids2;

  /* P2K_SOLWATCH=1 samples the coils at two points, and the pair is the whole argument for
     declaring FLIP_SOL: here, right after this driver publishes them, and again in
     SWITCH_UPDATE, which the core calls from inside core_updateSw() above - i.e. after its
     "fake solenoids if not CPU controlled" has cleared the low byte of solenoids2. Without
     FLIP_SOL the second point never sees a flipper coil at all. */
  if (p2k_solwatch()) {
    static int pubWas = -1;
    const int now = (int)(solenoids2 & 0xff);
    if (now != pubWas) {
      printf("[p2k sol2 pub] frame %d: %02x\n", p2k_bringupFrame, now);
      fflush(stdout);
      pubWas = now;
    }
  }
}

/* A PinMAME video renderer rather than a MAME VIDEO_UPDATE. The difference matters: with
   MDRV_VIDEO_UPDATE overridden, core_gen() never runs, and it is core_gen() that walks the
   display layout - which is what feeds libpinmame's display export. Declared in p2k_disp below
   as a CORE_VIDEO layout, exactly as byvidpin.c does for Baby Pac-Man. */
static PINMAME_VIDEO_UPDATE(p2k_video) {
  static UINT32 *frame = NULL;
  static int announced = 0;
  unsigned width = 0, height = 0, count, x, y;

  if (!frame) frame = (UINT32 *)malloc(P2K_MAX_PIXELS * sizeof(UINT32));
  if (!frame) return;

  p2k_sync_io();

  count = p2k_pinmame_frame(frame, P2K_MAX_PIXELS, &width, &height);
  if (!count || !width || !height) { fillbitmap(bitmap, 0, cliprect); return; }
  if (!announced) {
    announced = 1;
    fprintf(stderr, "[p2k video] %ux%u source into a %ux%u %d bpp bitmap (lines doubled)\n",
            width, height, width, height * P2K_LINE_DOUBLE, bitmap->depth);
  }

  if (width > (unsigned)bitmap->width) width = bitmap->width;
  if (height * P2K_LINE_DOUBLE > (unsigned)bitmap->height)
    height = (unsigned)bitmap->height / P2K_LINE_DOUBLE;

  for (y = 0; y < height; y++) {
    /* Video memory holds the picture upside down and the right way round, not mirrored:
       turning only the row order back makes the machine's own text (COIN DOOR IS OPEN /
       Revenge From Mars - 50070 - 1.5) legible. Measured by reading the bitmap back, and
       worth stating because it is the opposite of what the cabinet's half-silvered mirror
       would suggest. */
    const UINT32 *src = &frame[(height - 1 - y) * width];
    unsigned d;
    for (d = 0; d < P2K_LINE_DOUBLE; d++) {
      const unsigned ty = y * P2K_LINE_DOUBLE + d;
      for (x = 0; x < width; x++) {
        const UINT32 rgb = src[x];
        if (bitmap->depth == 32)
          ((UINT32 *)bitmap->line[ty])[x] = rgb;
        else                                                    /* 15 bit direct: RGB555 */
          ((UINT16 *)bitmap->line[ty])[x] = (UINT16)((((rgb >> 19) & 0x1f) << 10) |
                                                     (((rgb >> 11) & 0x1f) << 5) |
                                                      ((rgb >> 3) & 0x1f));
      }
    }
  }
  height *= P2K_LINE_DOUBLE;          /* from here on, what is in the bitmap */

  /* P2K_VIDEO_PPM=<path>: read the bitmap back once and write it out. Proof that what PinMAME
     holds is a picture, and that the pixel format written into it is the one it expects. */
  {
    static int frames = 0;
    static int lastAt = -1;
    const char *out = getenv("P2K_VIDEO_PPM");
    const char *when = getenv("P2K_VIDEO_PPM_AT");
    int hit = 0;
    char path[512];
    frames = p2k_bringupFrame ? p2k_bringupFrame : frames + 1;
    /* P2K_VIDEO_PPM_AT takes a comma separated list; each frame lands in <path>.<frame>.ppm so a
       sequence can be followed, not just one moment. */
    if (out && when) {
      const char *q = when;
      while (*q) {
        const int at = (int)strtol(q, NULL, 10);
        if (at > lastAt && frames >= at) { hit = 1; lastAt = at; break; }
        q = strchr(q, ','); if (!q) break; q++;
      }
    } else if (out && frames >= 600 && lastAt < 0) { hit = 1; lastAt = 600; }
    if (hit) {
      FILE *f;
      snprintf(path, sizeof path, "%s.%d.ppm", out, lastAt);
      f = fopen(path, "wb");
      if (f) {
        fprintf(f, "P6\n%u %u\n255\n", width, height);
        for (y = 0; y < height; y++) {
          for (x = 0; x < width; x++) {
            unsigned r, g, b;
            if (bitmap->depth == 32) {
              const UINT32 c = ((UINT32 *)bitmap->line[y])[x];
              r = (c >> 16) & 0xff; g = (c >> 8) & 0xff; b = c & 0xff;
            } else {
              const UINT16 c = ((UINT16 *)bitmap->line[y])[x];
              r = ((c >> 10) & 0x1f) << 3; g = ((c >> 5) & 0x1f) << 3; b = (c & 0x1f) << 3;
            }
            fputc((int)r, f); fputc((int)g, f); fputc((int)b, f);
          }
        }
        fclose(f);
        fprintf(stderr, "[p2k video] wrote %s from the PinMAME bitmap\n", out);
      }
    }
  }
}

/* Which ROM set the MediaGX side should load. The subsystem reads its files by prefix
   (<prefix>_u100.rom and so on), and the driver name carries it: rfmpb -> rfm, swe1pb -> swe1. */
static const char *p2k_romPrefix(void) {
  static char prefix[16];
  const char *name = (Machine && Machine->gamedrv) ? Machine->gamedrv->name : "rfmpb";
  size_t n = strlen(name);
  if (n > 2 && strcmp(name + n - 2, "pb") == 0) n -= 2;   /* drop the driver's "pb" suffix */
  if (n >= sizeof prefix) n = sizeof prefix - 1;
  memcpy(prefix, name, n);
  prefix[n] = 0;
  return prefix;
}

static SWITCH_UPDATE(p2k);   /* defined with the input ports below */

/* Switch numbering. PinMAME's base driver installs a *sequential* scheme (core_swSeq2m: matrix
   index = number + 7), but this machine numbers its switches by column and row - and so does the
   remote debugger, which emits num = column*10 + row + 1. Without this the numbers in the game's
   own tables land somewhere else entirely: core_setSw(13) for the start button ended up at column
   2 row 5, which is Left Loop (Low). Measured, not guessed - the row the board handed out was
   0x10 on column 1 instead of 0x04 on column 0.

   Row is 0-based coming in from the matrix side and 1-based in a switch number, hence the +1. */
static int p2k_sw2m(int no)          { return (no / 10) * 8 + (no % 10) - 1; }
static int p2k_m2sw(int col, int row) { return col * 10 + row + 1; }

/* What survives a power cycle. The machine keeps three things: the CMOS it stores settings, audits
   and its error log in, the PLX EEPROM behind the PCI bridge, and the 8 MB update flash. The first
   two are persisted here; the update flash is not, because it is supplied from outside during
   bring-up (P2K_NVRAM_UPDATES) and an 8 MB NVRAM file would quietly take precedence over it.

   PinMAME reads its NVRAM file before the machine is built and writes it after the machine is
   gone, so the bytes live in these buffers in between: the handler fills them on load, MACHINE_INIT
   pushes them into the machine, and the handler pulls them back out on save. */
#define P2K_NV_CMOS_SIZE   0x30000
#define P2K_NV_EEPROM_SIZE 0x80

static UINT8 p2k_nvCmos[P2K_NV_CMOS_SIZE];
static UINT8 p2k_nvEeprom[P2K_NV_EEPROM_SIZE];
static int   p2k_nvLoaded = 0;

static NVRAM_HANDLER(p2k) {
  /* No harvesting here on the way out - by the time PinMAME saves, the machine is gone. See
     MACHINE_STOP below, which is where the bytes are taken. */
  core_nvram(file, read_or_write, p2k_nvCmos,   P2K_NV_CMOS_SIZE,   0x00);
  core_nvram(file, read_or_write, p2k_nvEeprom, P2K_NV_EEPROM_SIZE, 0x00);
  /* Only adopt these if they really came from a file. With no file core_nvram() fills the
     buffers with zeros, and pushing those into the machine would wipe the PLX EEPROM defaults
     that reset() writes - which stops the machine booting at all. */
  if (!read_or_write) p2k_nvLoaded = (file != NULL);
}

/* P2K_NAMES=1 prints the machine's own device map once at startup: PinMAME switch number, coil
   driver number and lamp number against the names the game itself uses. PinMAME has nowhere to
   hang these, so this is the one place they are visible without a debugger that knows about them. */
static void p2k_dumpNames(void) {
  int i;
  if (!getenv("P2K_NAMES")) return;
  printf("[p2k names] switches (PinMAME number = column*10 + row):\n");
  for (i = 0; p2k_switch_names[i].name; i++)
    printf("   sw %3d  %s\n", p2k_switch_names[i].num, p2k_switch_names[i].name);
  printf("[p2k names] coils (driver number, solenoid bit = driver - 1):\n");
  for (i = 0; p2k_coil_names[i].name; i++)
    printf("   coil %2d  %s\n", p2k_coil_names[i].driver, p2k_coil_names[i].name);
  printf("[p2k names] lamps:\n");
  for (i = 0; p2k_lamp_names[i].name; i++)
    printf("   lamp %2d  %s\n", p2k_lamp_names[i].lamp, p2k_lamp_names[i].name);
  fflush(stdout);
}

static MACHINE_INIT(p2k) {
  p2k_dumpNames();
  p2k_pinmame_start(p2k_romPrefix());
  if (p2k_nvLoaded) {                        /* whatever PinMAME had on file, after the reset
                                                that fills in the EEPROM defaults */
    p2k_pinmame_nvram_set(0, p2k_nvCmos,   P2K_NV_CMOS_SIZE);
    p2k_pinmame_nvram_set(1, p2k_nvEeprom, P2K_NV_EEPROM_SIZE);
  }
  sndbrd_0_init(SNDBRD_DCSP2K, DCS_CPUNO, memory_region(DCS_ROMREGION), NULL, NULL);
}
/* Take the machine's persistent blocks before letting go of it.
/
/  run_machine_core() saves NVRAM *after* cpu_run() returns, and cpu_run()'s own cpu_post_run()
/  calls machine_stop first - so the driver's NVRAM handler runs when there is no machine left to
/  ask. Harvesting in the handler's save branch, which is the obvious place, wrote a file of
/  196828 zero bytes: nothing was saved, and restoring those zeros over the PLX EEPROM defaults
/  stopped the next boot dead at "STARTING UPDATE GAME CODE". */
static MACHINE_STOP(p2k) {
  p2k_pinmame_nvram_get(0, p2k_nvCmos,   P2K_NV_CMOS_SIZE);
  p2k_pinmame_nvram_get(1, p2k_nvEeprom, P2K_NV_EEPROM_SIZE);
  p2k_pinmame_stop();
}

MACHINE_DRIVER_START(p2k)
	MDRV_IMPORT_FROM(PinMAME)
	MDRV_CORE_INIT_RESET_STOP(p2k, NULL, p2k)
	MDRV_SWITCH_UPDATE(p2k)
	MDRV_SWITCH_CONV(p2k_sw2m, p2k_m2sw)
	MDRV_NVRAM_HANDLER(p2k)
	MDRV_CPU_ADD_TAG("mcpu", MEDIAGX, 20000000)
	MDRV_CPU_MEMORY(p2k_readmem, p2k_writemem)
	MDRV_IMPORT_FROM(wmssnd_dcs3)
	/* 480 rows, not the 240 the frame buffer holds: core_initDisplaySize() forces the visible
	   height to Machine->drv->screen_height, so the layout's row count alone does not size the
	   window - these two do. See P2K_LINE_DOUBLE above for why the picture is twice as tall. */
	MDRV_SCREEN_SIZE(640, 240 * P2K_LINE_DOUBLE)
	MDRV_VISIBLE_AREA(0, 639, 0, 240 * P2K_LINE_DOUBLE - 1)
	MDRV_VIDEO_ATTRIBUTES(VIDEO_TYPE_RASTER | VIDEO_RGB_DIRECT)
MACHINE_DRIVER_END

/* The cabinet and coin door, in the shape the pinball driver board reports them. The board keeps
   these apart from the playfield matrix: index 0x00 is the coin inputs, 0x01 the cabinet, 0x03 the
   coin door's diagnostic buttons - so they are carried in PinMAME's dedicated columns 10, 11 and a
   twelfth column for the diagnostics, and p2k_switch_update() below fills them.

   Bit assignments are MAME's (src/mame/drivers/pinball2k.cpp, its keyboard handler); keys follow
   PinMAME's WPC convention instead of MAME's, so 7/8/9/0 are Enter/Up/Down/Escape and END toggles
   the coin door. The board's own coin door bit reads "closed" when set - the machine reports COIN
   DOOR IS OPEN with the bit clear, which is the state it powers up in here. */
INPUT_PORTS_START(rfmpb)
	CORE_PORTS
	SIM_PORTS(1)
	PORT_START /* 2: CORE_COREINPORT */
		COREPORT_BITDEF(  0x0001, IPT_COIN1,        IP_KEY_DEFAULT)
		COREPORT_BITDEF(  0x0002, IPT_COIN2,        IP_KEY_DEFAULT)
		COREPORT_BITDEF(  0x0004, IPT_COIN3,        KEYCODE_3)
		COREPORT_BITDEF(  0x0008, IPT_COIN4,        KEYCODE_4)
		COREPORT_BIT(     0x0010, "Enter",          KEYCODE_7)
		COREPORT_BIT(     0x0020, "Up",             KEYCODE_8)
		COREPORT_BIT(     0x0040, "Down",           KEYCODE_9)
		COREPORT_BIT(     0x0080, "Escape",         KEYCODE_0)
		COREPORT_BITTOG(  0x0100, "Coin Door",      KEYCODE_END)
		COREPORT_BITDEF(  0x0200, IPT_START1,       IP_KEY_DEFAULT)
		COREPORT_BIT(     0x0400, "Plumb Tilt",     KEYCODE_INSERT)
		COREPORT_BIT(     0x0800, "Slam Tilt",      KEYCODE_HOME)
		COREPORT_BIT(     0x1000, "Left Action",    KEYCODE_LCONTROL)
		COREPORT_BIT(     0x2000, "Right Action",   KEYCODE_RCONTROL)
		COREPORT_BIT(     0x4000, "Launch Ball",    KEYCODE_ENTER)
INPUT_PORTS_END

#define input_ports_swe1pb input_ports_rfmpb

/*-- Switch numbers, read out of the game's own switch table: every handler record carries the
     number, and number = 100 + (column-1)*8 + (row-1). Columns 1-9 are the playfield matrix,
     column 10 the coin door's diagnostic buttons, column 11 the cabinet - which is exactly how
     the driver board reports them (registers 0x04, 0x03 and 0x01). Two independent checks that
     the scheme is right: the start button lands at column 1 row 3, the one coordinate MAME's
     driver spells out, and column 11 rows 5-8 are right flipper, left flipper, right action,
     left action - MAME's cabinet register bits 4 to 7. See src/p2k/README.md for the full list. --*/
#define swStartButton      13
#define swLaunchButton     23
#define swEscape          101
#define swDown            102
#define swUp              103
#define swEnter           104
#define swSlamTilt        111
#define swPlumbTilt       113
#define swCoinDoorClosed  112
#define swRFlipperButton  115
#define swLFlipperButton  116
#define swRActionButton   117
#define swLActionButton   118
/* Revenge From Mars has a launch button on the playfield matrix rather than the cabinet column;
   Star Wars Episode 1 has none - it has a hand plunger - and nothing is named at this position in
   its switch table, so pressing it there is simply ignored. */
#define swLaunchButton     23

/*-- the driver board's own bit numbering, from MAME's driver --*/
#define P2K_CAB_SLAMTILT   0x01
#define P2K_CAB_COINDOOR   0x02
#define P2K_CAB_PLUMBTILT  0x04
#define P2K_CAB_RFLIPPER   0x10
#define P2K_CAB_LFLIPPER   0x20
#define P2K_CAB_RACTION    0x40
#define P2K_CAB_LACTION    0x80

/* Up and Down are the other way round from MAME's header comment - measured on the running game
   (holding 0x02 walks the master volume down, 0x04 walks it up) and confirmed by the game's own
   switch table, which names column 10 rows 1 to 4 Escape, Down, Up, Enter. */
#define P2K_DIAG_ESCAPE    0x01
#define P2K_DIAG_DOWN      0x02
#define P2K_DIAG_UP        0x04
#define P2K_DIAG_ENTER     0x08

static SWITCH_UPDATE(p2k) {
	if (inports) {
		const int in = inports[CORE_COREINPORT];
		const int flip = inports[CORE_FLIPINPORT];

		/* Coin inputs. The board does not put them in the low bits: MAME's driver has the three
		   coin keys on bits 1, 2 and 7 of register 0x00, and setting bit 0 does nothing at all -
		   which is exactly what a coin mapped there did here. The fourth port bit has no known
		   position, so it stays unmapped rather than guessed. */
		coreGlobals.swMatrix[CORE_COINDOORSWCOL] =
			((in & 0x0001) ? 0x02 : 0) |
			((in & 0x0002) ? 0x04 : 0) |
			((in & 0x0004) ? 0x80 : 0);

		coreGlobals.swMatrix[11] =
			((in   & 0x0800) ? P2K_CAB_SLAMTILT  : 0) |
			((in   & 0x0100) ? P2K_CAB_COINDOOR  : 0) |
			((in   & 0x0400) ? P2K_CAB_PLUMBTILT : 0) |
			((flip & CORE_LRFLIPKEY) ? P2K_CAB_RFLIPPER : 0) |
			((flip & CORE_LLFLIPKEY) ? P2K_CAB_LFLIPPER : 0) |
			((in   & 0x2000) ? P2K_CAB_RACTION   : 0) |
			((in   & 0x1000) ? P2K_CAB_LACTION   : 0);

		coreGlobals.swMatrix[10] =
			((in & 0x0080) ? P2K_DIAG_ESCAPE : 0) |
			((in & 0x0020) ? P2K_DIAG_UP     : 0) |
			((in & 0x0040) ? P2K_DIAG_DOWN   : 0) |
			((in & 0x0010) ? P2K_DIAG_ENTER  : 0);

		core_setSw(swStartButton, in & 0x0200);
		p2k_keyLaunch = (in & 0x4000) ? 1 : 0;
		core_setSw(swLaunchButton, p2k_keyLaunch);
	}

	/* ---------------------------------------------------------------------------------------
	   BRING-UP SCAFFOLDING - not part of the driver, and not wanted in a release.

	   A standalone build has no playfield, and the machine will not run without one: its ball
	   devices do not merely read switches, they kick and then wait for switches to change. With
	   nothing answering, a device process stays alive forever and MultiDevice::game_start_check
	   refuses to start a game around it. On real hardware this feedback is the playfield; under
	   VPinMAME it is the table. This is a stand-in good enough to satisfy the devices.

	   Two constraints, both measured and both easy to get wrong:

	   - Optos rest at a 1. Trough 42-45, jam 41, popper 46 and lockup 51 carry bit 0x08 in their
	     SwitchTable entry; nothing inverts on the way in, and SwitchWork_16ms's init branch
	     pre-sets exactly those bits. Switch 18, the shooter lane, is not an opto.
	   - Start at rest and change nothing until the machine has initialised. Presenting a full
	     trough from frame zero is not "four balls in the machine", it is four switches that broke
	     during power-up, and it hangs the machine outright. P2K_BALLSAT (default 1500) is when
	     the balls appear.

	   P2K_TROUGH=<n>      n balls, placed in the trough once the machine is up
	   P2K_BALLSAT=<frame> when that happens
	   P2K_DRAIN=<frames>  how long a launched ball stays in play (default 300)
	   P2K_LANEHOLD=<f>    how long the lane switch stays closed after the autoplunger (default 20)
	   P2K_HANDPLUNGE=<f>  for a machine with no autoplunger coil - swe1pb has none - let a ball
	                       leave the shooter lane by itself after f frames, as a person would
	   P2K_DOORCLOSE=<f>   hold the coin door open until here, then close it - the *edge* is what
	                       brings up high voltage (Game::m_sw_coin_door_callback_irq), a door that
	                       was never open produces none and no coil ever fires
	   P2K_PLAY="<frame>:<what>[:<hold>],..." with what one of coin, start, enter, up, down, esc.
	                       The per-event hold matters: a coin held too long is not counted at all
	                       (8 frames gives credits, 120 gives none), the start button wants more.
	   --------------------------------------------------------------------------------------- */
	{
		enum { B_TROUGH, B_TO_LANE, B_LANE, B_LEAVING, B_PLAY };
		static int st[8], due[8], nballs = -1, placed = 0;
		static int ejectWas = 0, plungeWas = 0;
		static int laneSince[8];
		const char *tr = getenv("P2K_TROUGH");
		const char *seq = getenv("P2K_PLAY");
		const char *dc = getenv("P2K_DOORCLOSE");
		int frame, i;
		/* Nothing here costs anything unless it is asked for. Everything below is behind one of
		   these three, and a release build simply never enters the block. */
		if (!tr && !seq && !dc) return;
		frame = ++p2k_bringupFrame;

		/* P2K_SOLWATCH=1: report every change in the pinball board's register 0x0c, the low byte
		   of solenoids2 - drivers 33-40, which is where the flipper coils live. A change log
		   rather than a sample: a power stroke is a few frames long and a periodic sample walks
		   straight past it. */
		if (p2k_solwatch()) {
			static int solWas = -1;
			const int now = (int)(coreGlobals.solenoids2 & 0xff);
			if (now != solWas) {
				printf("[p2k sol2] frame %d: %02x  33:%d 34:%d 35:%d 36:%d 37:%d 38:%d 39:%d 40:%d\n",
					frame, now,
					(now >> 0) & 1, (now >> 1) & 1, (now >> 2) & 1, (now >> 3) & 1,
					(now >> 4) & 1, (now >> 5) & 1, (now >> 6) & 1, (now >> 7) & 1);
				fflush(stdout);
				solWas = now;
			}
		}

		if (seq || dc) {
			const char *hs = getenv("P2K_PLAYHOLD");
			const int hold = hs ? (int)strtol(hs, NULL, 10) : 8;
			const char *p = seq;
			int coin = 0, diag = 0, start = 0, cab = 0, launch = 0;
			/* Any playfield switch can be pulsed as "sw<number>", so a target or a jet needs no
			   code of its own. They are collected once and cleared every frame before the active
			   ones are set - core_setSw() latches, and a switch left closed reads as stuck. */
			static int swList[16], swCount = -1;
			int k;
			if (swCount < 0) {
				const char *q = seq;
				swCount = 0;
				while (q && *q && swCount < 16) {
					const char *c2 = strchr(q, ':');
					if (c2 && !strncmp(c2 + 1, "sw", 2)) {
						const int n = (int)strtol(c2 + 3, NULL, 10);
						if (n > 0) swList[swCount++] = n;
					}
					q = strchr(q, ','); if (q) q++;
				}
			}
			for (k = 0; k < swCount; k++) core_setSw(swList[k], 0);
			if (dc && frame >= (int)strtol(dc, NULL, 10)) cab |= P2K_CAB_COINDOOR;
			while (p && *p) {
				const int at = (int)strtol(p, NULL, 10);
				const char *c = strchr(p, ':');
				int thisHold = hold;
				if (c) { const char *h = strchr(c + 1, ':');
				         if (h && (!strchr(p, ',') || h < strchr(p, ','))) thisHold = (int)strtol(h + 1, NULL, 10); }
				if (c && frame >= at && frame < at + thisHold) {
					c++;
					if      (!strncmp(c, "coin",  4)) coin |= 0x02;
					else if (!strncmp(c, "start", 5)) start = 1;
					else if (!strncmp(c, "enter", 5)) diag |= P2K_DIAG_ENTER;
					else if (!strncmp(c, "up",    2)) diag |= P2K_DIAG_UP;
					else if (!strncmp(c, "down",  4)) diag |= P2K_DIAG_DOWN;
					else if (!strncmp(c, "esc",   3)) diag |= P2K_DIAG_ESCAPE;
					else if (!strncmp(c, "lflip", 5)) cab  |= P2K_CAB_LFLIPPER;
					else if (!strncmp(c, "rflip", 5)) cab  |= P2K_CAB_RFLIPPER;
					else if (!strncmp(c, "laction", 7)) cab |= P2K_CAB_LACTION;
					else if (!strncmp(c, "raction", 7)) cab |= P2K_CAB_RACTION;
					/* the launch button is a playfield switch, not a cabinet one - the game
					   fires the autoplunger off it once a ball waits in the shooter lane */
					else if (!strncmp(c, "launch", 6)) launch = 1;
					else if (!strncmp(c, "sw", 2)) core_setSw((int)strtol(c + 2, NULL, 10), 1);
					if (frame == at) { printf("[p2k play] %.7s at frame %d\n", c, frame); fflush(stdout); }
				}
				p = strchr(p, ','); if (p) p++;
			}
			coreGlobals.swMatrix[CORE_COINDOORSWCOL] = coin;
			coreGlobals.swMatrix[10] = diag;
			coreGlobals.swMatrix[11] = cab;
			core_setSw(swStartButton, start);
			/* OR rather than assign: this runs after the keyboard above and writes the
			   switch every frame, so assigning would make the Launch Ball key dead in exactly
			   the configuration that needs it - the ball model on, the player at the keyboard. */
			core_setSw(swLaunchButton, launch || p2k_keyLaunch);
		}

		if (tr) {
			const char *ba = getenv("P2K_BALLSAT");
			const int ballsAt = ba ? (int)strtol(ba, NULL, 10) : 1500;
			const char *dr = getenv("P2K_DRAIN");
			const int playtime = dr ? (int)strtol(dr, NULL, 10) : 300;
			const char *lh = getenv("P2K_LANEHOLD");
			const int lanehold = lh ? (int)strtol(lh, NULL, 10) : 20;
			const char *hp = getenv("P2K_HANDPLUNGE");
			const int handplunge = hp ? (int)strtol(hp, NULL, 10) : 0;
			const int eject  = (coreGlobals.solenoids & (1u << 8))  ? 1 : 0;   /* driver 9  */
			const int plunge = (coreGlobals.solenoids & (1u << 14)) ? 1 : 0;   /* driver 15 */
			int inTrough = 0, busy = 0, lane = 0;

			if (nballs < 0) { nballs = (int)strtol(tr, NULL, 10);
			                  if (nballs < 0) nballs = 0; if (nballs > 8) nballs = 8; }
			if (!placed && frame >= ballsAt) {
				placed = 1;
				for (i = 0; i < nballs; i++) { st[i] = B_TROUGH; due[i] = 0; }
				printf("[p2k ball] %d balls into the trough at frame %d\n", nballs, frame);
				fflush(stdout);
			}
			for (i = 0; placed && i < nballs; i++) {
				if (st[i] == B_TO_LANE && frame >= due[i]) {
					st[i] = B_LANE;
					laneSince[i] = frame;
					printf("[p2k ball] %d in the shooter lane at %d\n", i, frame); fflush(stdout);
				}
				if (st[i] == B_LEAVING && frame >= due[i]) {
					st[i] = B_PLAY; due[i] = frame + playtime;
					printf("[p2k ball] %d left the lane at %d\n", i, frame); fflush(stdout);
				}
				if (st[i] == B_PLAY && frame >= due[i]) {
					st[i] = B_TROUGH;
					printf("[p2k ball] %d drained at %d\n", i, frame); fflush(stdout);
				}
			}
			for (i = 0; placed && i < nballs; i++) {
				if (st[i] == B_TROUGH)  inTrough++;
				if (st[i] == B_TO_LANE) busy++;
				if (st[i] == B_LANE || st[i] == B_LEAVING) lane++;
			}
			if (eject && !ejectWas && placed && !busy && !lane)
				for (i = 0; i < nballs; i++)
					if (st[i] == B_TROUGH) {
						st[i] = B_TO_LANE; due[i] = frame + 30;
						printf("[p2k ball] %d ejected at %d, %d left\n", i, frame, inTrough - 1);
						fflush(stdout);
						break;
					}
			ejectWas = eject;
			if (plunge && !plungeWas)
				for (i = 0; i < nballs; i++)
					if (st[i] == B_LANE) {
						st[i] = B_LEAVING; due[i] = frame + lanehold;
						printf("[p2k ball] %d launched at %d\n", i, frame); fflush(stdout);
						break;
					}
			plungeWas = plunge;

			/* A machine without an autoplunger. Revenge From Mars has one - driver 15, fired by
			   the game when the launch button is pressed - and the model waits for it. Star Wars
			   Episode 1 has no such coil: its own coil table lists a trough eject, slings, jets,
			   saucers and flippers, and nothing that launches a ball. It has a hand plunger, and
			   the ball leaves the lane because a person pulled it.

			   P2K_HANDPLUNGE=<frames> models that person: a ball that has sat in the shooter lane
			   that long leaves on its own. Without it a game on Episode 1 stops at the lane. */
			if (handplunge)
				for (i = 0; i < nballs; i++)
					if (st[i] == B_LANE && frame - laneSince[i] >= handplunge) {
						st[i] = B_LEAVING; due[i] = frame + lanehold;
						printf("[p2k ball] %d plunged by hand at %d\n", i, frame); fflush(stdout);
						break;
					}

			/* --- the playfield ------------------------------------------------------------
			   While a ball is in play the model walks it over the playfield: every P2K_HITRATE
			   frames it closes the next switch in the table below for P2K_HITLEN frames. The
			   order is fixed rather than random so a run can be repeated exactly - the point is
			   to keep the game fed with events, not to be a physics engine.

			   The table is the game's own switch numbers (see p2k_names.h): the three jets, both
			   slingshots, the centre and martian targets, the top lanes, the loops and the ramps.
			   The outlanes (16, 27) are deliberately absent - draining is the drain timer's job,
			   so a ball's length in play stays under P2K_DRAIN. */
			static const int pfSwitches[] = {
				63, 64, 65,          /* left, right, bottom jet   */
				61, 62,              /* slingshots                */
				36, 35, 34, 33,      /* centre targets 1..4       */
				73, 72, 71,          /* martian targets 1..3      */
				85, 86, 87,          /* martian targets 7..5      */
				77, 76,              /* left and right top lane   */
				78, 25, 68, 67,      /* left and right loops      */
				11, 28, 52, 12,      /* ramp entrances and exits  */
				74                   /* centre loop rollover      */
			};
			static int pfIdx = 0, pfSw = 0, pfUntil = 0, pfNext = 0;
			if (getenv("P2K_PLAYFIELD")) {
				const char *hr = getenv("P2K_HITRATE");
				const char *hl = getenv("P2K_HITLEN");
				const int hitrate = hr ? (int)strtol(hr, NULL, 10) : 60;
				const int hitlen  = hl ? (int)strtol(hl, NULL, 10) : 5;
				int anyInPlay = 0;
				for (i = 0; i < nballs; i++) if (st[i] == B_PLAY) anyInPlay = 1;
				if (pfSw && frame >= pfUntil) { core_setSw(pfSw, 0); pfSw = 0; }
				if (!anyInPlay) { pfNext = frame + hitrate; }
				else if (!pfSw && frame >= pfNext) {
					pfSw = pfSwitches[pfIdx++ % (int)(sizeof pfSwitches / sizeof pfSwitches[0])];
					pfUntil = frame + hitlen;
					pfNext  = frame + hitrate;
					core_setSw(pfSw, 1);
				}
			}

			/* the optos, at rest until the balls arrive; the lane is not an opto */
			for (i = 0; i < 4; i++) core_setSw(42 + i, (i < inTrough) ? 0 : 1);
			core_setSw(41, 1);
			core_setSw(46, 1);
			core_setSw(51, 1);
			core_setSw(18, lane ? 1 : 0);
		}
	}
}

/* PinMAME insists on a ROM region; the machine loads its real ROM set itself, so this only
   pins the game to its boot flash. Point the ROM path at a directory holding that file. */
/* The MediaGX side loads its own ROMs; what has to be declared here is the sound board's: one
   unified 0x600000-word sound address space with the flash at word 0, U109 at 0x200000 and U110
   at 0x400000. DCS_P2K_SNDREGION is deliberately not declared - with a single region the SDRC
   runs in its EPROM mode, which is the page register this firmware programs.

   The two sample chips sit there flat, one after the other, NOT interleaved at 32-bit stride as
   docs/pin2k_sound.md suggests. The firmware settles it: sound command 0x001b walks a checksum
   table held in the sound flash (three regions: flash, U109, U110) and byte-sums each one. For
   Star Wars Episode 1, whose sample dumps are good, the flat layout reproduces the expected
   0x25db/0x8e72 exactly, while the interleaved one gives 0xef29/0xc424. MAME's driver loads
   them flat as well. */
#define ROM_P2K(name, flash, u109, u110) \
ROM_START(name) \
	NORMALREGION(0x100000, REGION_CPU1) \
		ROM_LOAD(flash, 0x0000, 0x100000, NO_DUMP) \
	NORMALREGION(ADSP2100_SIZE, DCS_CPUREGION) \
	NORMALREGION(0x8000*2,      DCS_P2K_SRAMREGION) \
	SOUNDREGION(0xc00000, DCS_ROMREGION) \
		ROM_LOAD        (flash, 0x000000, 0x100000, NO_DUMP) \
		ROM_LOAD        (u109,  0x400000, 0x400000, NO_DUMP) \
		ROM_LOAD        (u110,  0x800000, 0x400000, NO_DUMP) \
ROM_END

/* file names as they are in the Encore set.

   A warning about that set's Revenge From Mars sample chips: rfm_u109.bin/rfm_u110.bin
   (CRC32 A20B2ABB/095ABEC9) are not the chips this sound flash expects. The board's own ROM
   checksum (sound command 0x001b) wants 0x08f8/0x54ac and computes 0x50a8 from these files, and
   no arrangement of them produces the expected value. MAME lists rfm_u109.rom = 385F1255 and
   rfm_u110.rom = 2258DBDE. The Episode 1 files below do match MAME and do satisfy their flash,
   so sound work belongs on swe1pb until proper RFM dumps turn up. */
ROM_P2K(rfmpb,  "rfm_28f800.rom",  "rfm_u109.bin",  "rfm_u110.bin")
ROM_P2K(swe1pb, "swe1_28f800.rom", "swe1_u109.rom", "swe1_u110.rom")

/* PinMAME's core wants a game description before it will build the machine. Pinball 2000 has
   no alphanumeric or dot matrix display - its video comes from the MediaGX frame buffer - so
   the layout is empty for now. */
static PINMAME_VIDEO_UPDATE(p2k_video);
/* 640x240, the machine's own screen. Declaring it as CORE_VIDEO is what tells the core there is a
   display at all: without it locals.hasDmdOrVideo stays clear and libpinmame invents a 128x32 DMD
   in its place, so a frontend would see a fake dot matrix and never the real picture. */
static core_tLCDLayout p2k_disp[] = {
  {0, 0, 240 * P2K_LINE_DOUBLE, 640, CORE_VIDEO, (genf *)p2k_video, NULL}, {0}
};
/* What PinMAME's core can be told about this machine. The lamp matrix is sixteen columns rather
   than eight, because the board drives eight columns with two row banks each, so eight custom
   columns are declared on top of the standard ones. The common switches are the ones the core and
   the remote debugger ask for by name; their numbers come from the game's own switch table
   (see src/p2k/README.md): start 13, plumb tilt 113, slam tilt 111, coin door 112. This machine
   reports no shooter lane switch of its own, so that one stays unset. */
/* The flippers are driven by the game, not faked by the core.
/
/  Without FLIP_SOL the core treats the machine as one whose flippers are not CPU controlled and
/  does this, once a frame (core.c, "fake solenoids if not CPU controlled"):
/
/      coreGlobals.solenoids2 &= 0xffffff00;
/      if (swFlip & CORE_SWLLFLIPBUTBIT) coreGlobals.solenoids2 |= CORE_LLFLIPSOLBITS;
/      if (swFlip & CORE_SWLRFLIPBUTBIT) coreGlobals.solenoids2 |= CORE_LRFLIPSOLBITS;
/
/  Those low eight bits of solenoids2 are exactly where this driver puts the pinball board's
/  register 0x0c - drivers 33-40 - so the game's own flipper coils were being wiped every frame
/  and replaced by a copy of the buttons. Earlier flipper measurements in src/p2k/README.md were
/  reading that copy, not the machine.
/
/  The game's numbering and the core's agree exactly, which is why nothing else has to move:
/
/      Treiber 33 Right Flipper Power   -> solenoids2 bit 0 = sLRFlipPow (45)
/      Treiber 34 Right Flipper Hold    -> solenoids2 bit 1 = sLRFlip    (46)
/      Treiber 35 Left Flipper Power    -> solenoids2 bit 2 = sLLFlipPow (47)
/      Treiber 36 Left Flipper Hold     -> solenoids2 bit 3 = sLLFlip    (48)
/
/  FLIP_SOL(x) also sets FLIP_EOS(x), and that part is deliberately masked off. EOS would put two
/  synthesised end-of-stroke switches into the flipper column at bits 0x01 and 0x04, and this
/  machine's cabinet column uses those two for slam tilt and plumb tilt - a held flipper would
/  read as a tilt. The machine has no end-of-stroke switches in its own switch table either. */
#define P2K_FLIPPERS (FLIP_SW(FLIP_L) | (FLIP_SOL(FLIP_L) & ~FLIP_EOS(FLIP_L)))

static core_tGameData p2kGameData = {
  0, p2k_disp,
  {P2K_FLIPPERS, 0, /*lampCol*/ 8, 0},
  NULL,
  {{0}, {0}, {swStartButton, swPlumbTilt, swSlamTilt, swCoinDoorClosed, 0}}
};

static void init_rfmpb(void)  { core_gameData = &p2kGameData; }
static void init_swe1pb(void) { core_gameData = &p2kGameData; }

/* GAME_NOT_WORKING makes MAME wait for a keypress on its warning screen before starting the
   CPU, which never comes when running headless - the machine would sit there forever. */
CORE_GAMEDEFNV(rfmpb,  "Pinball 2000: Revenge From Mars",     1999, "Midway", p2k, 0)
CORE_GAMEDEFNV(swe1pb, "Pinball 2000: Star Wars Episode I",   1999, "Midway", p2k, 0)

#endif /* HAS_MEDIAGX */
