/* Generated from the game's own device tables - do not edit by hand. */
#ifndef P2K_NAMES_H
#define P2K_NAMES_H

/* switch number = 100 + (column-1)*8 + (row-1); PinMAME numbers it column*10 + row */
static const struct { int num; const char *name; } p2k_switch_names[] = {
  {  11, "Right Ramp Entrance" },
  {  12, "Left Ramp Exit" },
  {  13, "Start Button" },
  {  15, "Drop Target Down" },
  {  16, "Left Outlane" },
  {  17, "Right Return Lane" },
  {  23, "Launch Button" },
  {  25, "Left Loop (Low)" },
  {  26, "Left Return Lane" },
  {  27, "Right Outlane" },
  {  28, "Right Ramp Exit" },
  {  31, "Center Loop Reed (Bottom)" },
  {  32, "Center Loop Reed (Top)" },
  {  33, "Center Target 4" },
  {  34, "Center Target 3" },
  {  35, "Center Target 2" },
  {  36, "Center Target 1" },
  {  37, "Martian Target 4 (Center)" },
  {  38, "Up/Down Ramp Up" },
  {  47, "Jet Exit" },
  {  52, "Left Ramp Entrance" },
  {  61, "Left Slingshot" },
  {  62, "Right Slingshot" },
  {  63, "Left Jet" },
  {  64, "Right Jet" },
  {  65, "Bottom Jet" },
  {  67, "Right Loop (Low)" },
  {  68, "Right Loop (High)" },
  {  71, "Martian Target 3 (L. Top.)" },
  {  72, "Martian Target 2 (L. Mid.)" },
  {  73, "Martian Target 1 (L. Bot.)" },
  {  74, "Center Loop Rollover" },
  {  75, "Center Deflector Panel" },
  {  76, "Right Top Lane" },
  {  77, "Left Top Lane" },
  {  78, "Left Loop (High)" },
  {  85, "Martian Target 7 (R. Bot.)" },
  {  86, "Martian Target 6 (R. Mid.)" },
  {  87, "Martian Target 5 (R. Top.)" },
  { 101, "'ESCAPE' BUTTON" },
  { 102, "'Down' Button" },
  { 103, "'Up' Button" },
  { 104, "'Enter' Button" },
  { 111, "Slam Tilt" },
  { 112, "Coin Door Closed" },
  { 115, "Right Flipper Button" },
  { 116, "Left Flipper Button" },
  { 117, "Right Action Button" },
  { 118, "Left Action Button" },
  { 0, NULL }
};

static const struct { int driver; const char *name; } p2k_coil_names[] = {
  {  1, "Left Martian" },
  {  2, "Right Martian" },
  {  3, "Jet Exit Post" },
  {  4, "Right Gate" },
  {  5, "Left Gate" },
  {  6, "Drop Target Down" },
  {  7, "Drop Target Up" },
  {  8, "Right Popper" },
  {  9, "Trough Eject" },
  { 10, "Left Sling" },
  { 11, "Right Sling" },
  { 12, "Left Jet" },
  { 13, "Right Jet" },
  { 14, "Bottom Jet" },
  { 15, "Autoplunger" },
  { 16, "Right Lockup" },
  { 17, "Center Arrow Flasher" },
  { 22, "Right Popper Flasher" },
  { 23, "Left Arch Flasher" },
  { 25, "Right Arch Flasher" },
  { 26, "Left Martian Flasher" },
  { 27, "Right Martian Flasher" },
  { 28, "Attack Mars Flasher" },
  { 33, "Right Flipper Power" },
  { 34, "Right Flipper Hold" },
  { 35, "Left Flipper Power" },
  { 36, "Left Flipper Hold" },
  { 37, "Lock Diverter Power" },
  { 38, "Lock Diverter Hold" },
  { 39, "Up/Down Ramp Power" },
  { 40, "Up/Down Ramp Hold" },
  { 48, "Ticket Dispenser" },
  { 53, "Start Button" },
  { 56, "Right Top Lane" },
  { 57, "Left Top Lane" },
  { 59, "Martian Target 4 (Center)" },
  { 60, "Center Loop Arrow" },
  { 62, "Tickets Low" },
  { 0, NULL }
};

static const struct { int lamp; const char *name; } p2k_lamp_names[] = {
  {  0, "Start Button" },
  {  2, "Right Top Lane" },
  {  3, "Left Top Lane" },
  {  4, "Martian Target 4 (Center)" },
  {  5, "Center Loop Arrow" },
  {  6, "Tickets Low" },
  {  8, "Launch Button" },
  {  9, "Coin Door Illumination" },
  { 10, "Mothership Multiball (Right)" },
  { 11, "Mothership Multiball (Left)" },
  { 12, "Left Return Lane" },
  { 13, "Left Outlane" },
  { 18, "Left Drain To Trough" },
  { 19, "Right Drain To Trough" },
  { 20, "Right Return Lane" },
  { 21, "Right Outlane" },
  { 22, "Right Popper Arrow" },
  { 23, "Extra Ball" },
  { 24, "Martian Attack" },
  { 25, "Stroke Of Luck" },
  { 26, "Left Side Spotlight" },
  { 27, "Center Arrow" },
  { 28, "Right Martian (High)" },
  { 29, "Right Martian (Low)" },
  { 30, "Multiball" },
  { 31, "Capture 2" },
  { 32, "Capture 1" },
  { 33, "Capture Zone Active" },
  { 34, "Shoot Again" },
  { 35, "Behind Center Targets" },
  { 36, "Upper R. Corner (Middle)" },
  { 38, "Shooter Lane 9 (Top)" },
  { 39, "Under R. Ramp (Low)" },
  { 40, "Under R. Ramp (High)" },
  { 41, "Upper R. Corner (Low)" },
  { 42, "Right Arch (Right)" },
  { 43, "Right Arch (Left)" },
  { 44, "Left Arch (Right)" },
  { 45, "Left Arch (Left)" },
  { 46, "Left Side 1 (Bottom)" },
  { 47, "Left Side 2" },
  { 48, "Left Side 3" },
  { 49, "Left Side 4 (Top)" },
  { 50, "Under Left Ramp (Bottom)" },
  { 51, "Under Left Ramp (Top)" },
  { 52, "Between L/B Jets" },
  { 53, "Upper Left Corner" },
  { 54, "Right Slingshot (Bottom)" },
  { 55, "Right Slingshot (Saucer)" },
  { 56, "Right Return Lane (Right)" },
  { 57, "Right Return Lane (Left)" },
  { 58, "Left Return Lane (Right)" },
  { 59, "Left Return Lane (Left)" },
  { 60, "Left Slingshot (Saucer)" },
  { 61, "Left Slingshot (Bottom)" },
  { 62, "Secret Weapon" },
  { 63, "Tower Struggle" },
  { 64, "Center Saucer Beam (Left)" },
  { 65, "Question Mark" },
  { 66, "Center Saucer Beam (Right)" },
  { 67, "Drive-In Demolition" },
  { 68, "Paris In Peril" },
  { 69, "Right Slingshot Spotlight" },
  { 70, "Big-O-Beam" },
  { 71, "Right Saucer Beam (Left)" },
  { 72, "Weapons" },
  { 73, "Saucer" },
  { 74, "Fuel" },
  { 75, "Left Saucer Beam (Right)" },
  { 76, "Center Saucer Beam (Center)" },
  { 77, "Left Slingshot Spotlight" },
  { 78, "Mars Kneads Women" },
  { 79, "Right Saucer Beam (Right)" },
  { 80, "Saucer Rim 9 (Right)" },
  { 81, "Saucer Rim 8" },
  { 82, "Saucer Rim 7" },
  { 83, "Saucer Rim 6" },
  { 84, "Saucer Rim 5" },
  { 86, "Martian Happy Hour" },
  { 87, "Alien Abduction" },
  { 88, "Left Saucer Beam (Left)" },
  { 89, "Saucer Rim 1 (Left)" },
  { 90, "Saucer Rim 2" },
  { 91, "Saucer Rim 3" },
  { 92, "Saucer Rim 4" },
  { 94, "Right Loop Arrow" },
  { 95, "Right Loop Circle" },
  { 0, NULL }
};

/*-- lookups; every table is short, and none of this is on a hot path --*/
static const char *p2k_switch_name(int num) {
  int i; for (i = 0; p2k_switch_names[i].name; i++)
    if (p2k_switch_names[i].num == num) return p2k_switch_names[i].name;
  return NULL;
}
static const char *p2k_coil_name(int driver) {
  int i; for (i = 0; p2k_coil_names[i].name; i++)
    if (p2k_coil_names[i].driver == driver) return p2k_coil_names[i].name;
  return NULL;
}
static const char *p2k_lamp_name(int lamp) {
  int i; for (i = 0; p2k_lamp_names[i].name; i++)
    if (p2k_lamp_names[i].lamp == lamp) return p2k_lamp_names[i].name;
  return NULL;
}

#endif /* P2K_NAMES_H */
