# lisy80 Makefile
# RTH 09.2016
# for pic eeprom testprg

CC      = /usr/bin/gcc
CFLAGS  = -Wall -g -D_REENTRANT -DDEBUG
LDFLAGS = -lwiringPi


#OBJ = hw_lib.o coils.o displays.o switches.o sound.o utils.o Tester.o
OBJ = utils.o hw_lib.o switches.o displays.o coils.o tpiceeprom.o

teeprom: $(OBJ)
	$(CC) $(CFLAGS) -o tpiceeprom $(OBJ) $(LDFLAGS)

%.o: ../%.c ../%.h
	$(CC) $(CFLAGS) -c $<

