# lisy80 Makefile
# RTH 11.2016
# for teeprom prog

CC      = /usr/bin/gcc
CFLAGS  = -Wall -g -D_REENTRANT -DDEBUG

#OBJ = hw_lib.o coils.o displays.o switches.o sound.o utils.o Tester.o
OBJ = eeprom.o teeprom.o

teeprom: $(OBJ)
	$(CC) $(CFLAGS) -o teeprom $(OBJ) $(LDFLAGS)

%.o: ../%.c ../%.h
	$(CC) $(CFLAGS) -c $<

