# lisy80 Makefile
# RTH 11.2016
# for tester prog

CC      = /usr/bin/gcc
CFLAGS  = -Wall -g -D_REENTRANT -DDEBUG
LDFLAGS = -lwiringPi
#LDFLAGS = -lbcm2835

#OBJ = hw_lib.o coils.o displays.o switches.o sound.o utils.o Tester.o
OBJ = utils.o hw_lib.o switches.o displays.o coils.o eeprom.o fileio.o Tester.o

tester: $(OBJ)
	$(CC) $(CFLAGS) -o Tester $(OBJ) $(LDFLAGS)

%.o: ../%.c ../%.h
	$(CC) $(CFLAGS) -c $<

