# lisy1 Makefile for socketserver
# RTH 04.2017

CC      = /usr/bin/gcc
CFLAGS  = -Wall -g -D_REENTRANT -DDEBUG
#LDFLAGS = -lwiringPi -lSDL2 -lSDL2_mixer
LDFLAGS = -lwiringPi
#LDFLAGS = -lbcm2835

OBJ = lisy.o fileio.o utils.o hw_lib.o switches.o displays.o coils.o eeprom.o opc.o fadecandy.o lisy1_control.o

lisy1_control: $(OBJ)
	$(CC) $(CFLAGS) -o lisy1_control $(OBJ) $(LDFLAGS)

%.o: ../%.c ../%.h
	$(CC) $(CFLAGS) -c $<

